<script setup>
import {ref,onMounted,computed} from 'vue';import api from '@/lib/axios';import {Plus,ReceiptText,CalendarDays,Check,Trash2,X,Repeat2,Bell} from 'lucide-vue-next';import {formatRupiah} from '@/utils/formatters';
const bills=ref([]),loading=ref(false),open=ref(false),editing=ref(null);const form=ref({name:'',amount:'',due_date:'',frequency:'monthly',status:'active',category:'',note:'',reminder_enabled:true});
const upcoming=computed(()=>bills.value.filter(x=>x.status==='active'));const monthly=computed(()=>upcoming.value.reduce((n,x)=>n+(x.frequency==='yearly'?Number(x.amount)/12:x.frequency==='weekly'?Number(x.amount)*4.33:x.frequency==='once'?0:Number(x.amount)),0));
async function load(){loading.value=true;try{const r=await api.get('/api/bills');bills.value=r.data.data||[]}finally{loading.value=false}}
function add(){editing.value=null;form.value={name:'',amount:'',due_date:new Date().toISOString().slice(0,10),frequency:'monthly',status:'active',category:'',note:'',reminder_enabled:true};open.value=true}
function edit(x){editing.value=x;form.value={...x,due_date:String(x.due_date).slice(0,10)};open.value=true}
async function save(){const payload={...form.value,amount:Number(form.value.amount)};if(editing.value)await api.put(`/api/bills/${editing.value.id}`,payload);else await api.post('/api/bills',payload);open.value=false;await load()}
async function paid(x){await api.post(`/api/bills/${x.id}/paid`);await load()}async function del(x){if(confirm(`Hapus tagihan ${x.name}?`)){await api.delete(`/api/bills/${x.id}`);await load()}}
function dueLabel(d){return new Date(d).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}onMounted(load);
</script>
<template><div class="page-shell">
<div class="page-heading"><div><span class="eyebrow">Planning</span><h1>Tagihan & langganan</h1><p>Simpan biaya rutin, tanggal jatuh tempo, dan status pembayaran agar pengeluaran wajib tidak terlewat.</p></div><button @click="add" class="primary-button"><Plus class="w-4 h-4"/>Tambah tagihan</button></div>
<div class="grid sm:grid-cols-3 gap-3"><div class="surface-card p-5"><span class="field-label">Tagihan aktif</span><strong class="text-2xl tracking-[-.04em]">{{upcoming.length}}</strong></div><div class="surface-card p-5 sm:col-span-2"><span class="field-label">Estimasi biaya rutin / bulan</span><strong class="text-2xl tracking-[-.04em] font-mono-money">{{formatRupiah(monthly)}}</strong></div></div>
<div class="surface-card overflow-hidden"><div class="p-5 border-b border-line-200 flex items-center justify-between"><div><h2 class="font-bold">Daftar tagihan</h2><p class="text-xs text-ink-500 mt-1">Klik item untuk mengubah data tanpa perlu menghapus.</p></div><ReceiptText class="w-5 h-5 text-primary-600"/></div><div v-if="!bills.length&&!loading" class="empty-state"><ReceiptText class="w-8 h-8"/><b>Belum ada tagihan</b><span>Tambahkan internet, listrik, subscription, cicilan, atau tagihan lainnya.</span></div><div class="divide-y divide-line-200"><div v-for="b in bills" :key="b.id" class="p-4 md:p-5 flex items-center gap-4 hover:bg-base-50 transition cursor-pointer" @click="edit(b)"><div class="w-11 h-11 rounded-2xl bg-primary-100 text-primary-600 grid place-items-center shrink-0"><Repeat2 v-if="b.frequency!=='once'" class="w-5 h-5"/><ReceiptText v-else class="w-5 h-5"/></div><div class="min-w-0 flex-1"><div class="flex items-center gap-2"><b class="text-sm truncate">{{b.name}}</b><span v-if="b.status==='paid'" class="text-[10px] px-2 py-0.5 rounded-full bg-income-100 text-income-600 font-bold">Lunas</span></div><div class="flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-ink-500 mt-1"><span class="flex gap-1 items-center"><CalendarDays class="w-3 h-3"/>{{dueLabel(b.due_date)}}</span><span>{{b.frequency}}</span><span v-if="b.reminder_enabled" class="flex gap-1 items-center"><Bell class="w-3 h-3"/>Reminder</span></div></div><b class="font-mono-money text-sm">{{formatRupiah(b.amount)}}</b><div class="hidden sm:flex gap-1" @click.stop><button v-if="b.status!=='paid'" @click="paid(b)" class="icon-button text-income-600" title="Tandai lunas"><Check class="w-4 h-4"/></button><button @click="del(b)" class="icon-button text-expense-600" title="Hapus"><Trash2 class="w-4 h-4"/></button></div></div></div></div>
<div v-if="open" class="fixed inset-0 z-50 bg-black/35 backdrop-blur-sm grid place-items-end sm:place-items-center p-0 sm:p-4" @click="open=false"><form @submit.prevent="save" class="bg-paper-0 w-full sm:max-w-lg rounded-t-[28px] sm:rounded-[24px] p-5 md:p-6 shadow-soft max-h-[90vh] overflow-auto" @click.stop><div class="flex justify-between items-start mb-5"><div><span class="eyebrow">{{editing?'Edit':'New'}}</span><h2 class="text-xl font-extrabold">{{editing?'Ubah tagihan':'Tambah tagihan'}}</h2></div><button type="button" @click="open=false" class="icon-button"><X class="w-4 h-4"/></button></div><div class="grid gap-4"><label><span class="field-label">Nama</span><input v-model="form.name" required class="w-full px-3" placeholder="Internet rumah"/></label><label><span class="field-label">Nominal</span><input v-model="form.amount" required type="number" min="0" class="w-full px-3" placeholder="350000"/></label><div class="grid grid-cols-2 gap-3"><label><span class="field-label">Jatuh tempo</span><input v-model="form.due_date" required type="date" class="w-full px-3"/></label><label><span class="field-label">Frekuensi</span><select v-model="form.frequency" class="w-full px-3"><option value="once">Sekali</option><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option><option value="yearly">Tahunan</option></select></label></div><label><span class="field-label">Kategori</span><input v-model="form.category" class="w-full px-3" placeholder="Utilities, subscription…"/></label><label><span class="field-label">Catatan</span><textarea v-model="form.note" class="w-full p-3 min-h-24"/></label><label class="flex gap-3 items-center text-sm"><input v-model="form.reminder_enabled" type="checkbox"/>Aktifkan pengingat</label><button class="primary-button w-full">{{editing?'Simpan perubahan':'Tambah tagihan'}}</button></div></form></div>
</div></template>
