<script setup>
import { ref } from 'vue';
import api from '@/lib/axios';
import logoImg from '@/assets/ledger-icon.png';
import { Mail, ArrowLeft, Loader2, CheckCircle2 } from 'lucide-vue-next';
const email = ref(''); const loading = ref(false); const sent = ref(false); const message = ref('');
async function submit(){ loading.value=true; message.value=''; try { const {data}=await api.post('/api/forgot-password',{email:email.value}); sent.value=true; message.value=data.message; } catch(e){ message.value=e.response?.data?.message || 'Permintaan belum dapat diproses. Coba lagi.'; } finally {loading.value=false;} }
</script>
<template><div class="min-h-screen bg-lavender-50 flex items-center justify-center p-4 font-body text-ink-900"><div class="w-full max-w-md bg-paper-0 border border-line-200 rounded-2xl p-6 md:p-8 shadow-card space-y-6"><div class="text-center space-y-3"><img :src="logoImg" class="w-20 mx-auto" alt="Ledger"><h1 class="font-display text-2xl font-bold">Lupa Password</h1><p class="text-sm text-ink-600">Masukkan email akun. Kami akan mengirim tautan reset password.</p></div><div v-if="sent" class="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-sm text-emerald-700 flex gap-3"><CheckCircle2 class="w-5 h-5 shrink-0"/><span>{{message}}</span></div><form v-else @submit.prevent="submit" class="space-y-4"><div><label class="block text-xs font-medium text-ink-600 mb-1.5">Alamat Email</label><div class="relative"><Mail class="absolute left-3 top-3 w-4 h-4 text-ink-400"/><input v-model.trim="email" required type="email" autocomplete="email" class="w-full h-10 pl-9 pr-3 border border-line-200 rounded-lg focus:border-indigo-600 focus:outline-none" placeholder="nama@email.com"></div></div><p v-if="message" class="text-xs text-rose-600">{{message}}</p><button :disabled="loading" class="w-full h-10 rounded-lg bg-indigo-600 text-white font-semibold text-sm disabled:opacity-50 flex justify-center items-center gap-2"><Loader2 v-if="loading" class="w-4 h-4 animate-spin"/>Kirim Link Reset</button></form><router-link to="/login" class="flex justify-center items-center gap-2 text-xs font-semibold text-indigo-600"><ArrowLeft class="w-4 h-4"/>Kembali ke login</router-link></div></div></template>
