<script setup>
import { onMounted, ref } from "vue";
import { MessageCircle, Copy, RefreshCw, Unplug } from "lucide-vue-next";
import api from "@/lib/axios";
import { useNotificationStore } from "@/stores/notification";
const notify=useNotificationStore(); const status=ref({connected:false}); const pairing=ref(null); const loading=ref(false);
async function load(){ const {data}=await api.get("/api/integrations/whatsapp"); status.value=data.data; }
async function createPair(){loading.value=true; try{const {data}=await api.post("/api/integrations/whatsapp/pairing"); pairing.value=data.data; notify.notify({message:"Kode pairing dibuat.",type:"success"});}finally{loading.value=false;}}
async function copy(){await navigator.clipboard.writeText(pairing.value.command);notify.notify({message:"Perintah pairing disalin.",type:"success"});}
async function disconnect(){if(!confirm("Putuskan WhatsApp dari Ledger?"))return; await api.delete("/api/integrations/whatsapp"); pairing.value=null; await load();}
onMounted(load);
</script>
<template><div class="space-y-6"><div><h1 class="font-display text-2xl md:text-3xl font-bold text-ink-900">WhatsApp Quick Add</h1><p class="text-sm text-ink-600 mt-1">Catat transaksi lewat chat WhatsApp dengan bahasa natural.</p></div><div class="max-w-2xl rounded-3xl border border-ink-200 bg-white p-6 space-y-5"><div class="flex items-center gap-3"><div class="rounded-2xl bg-ink-900 p-3 text-white"><MessageCircle :size="22"/></div><div><p class="font-semibold text-ink-900">Status integrasi</p><p class="text-sm text-ink-600">{{ status.connected ? `Terhubung • ${status.phone_number}` : 'Belum terhubung' }}</p></div></div><template v-if="!status.connected"><button @click="createPair" :disabled="loading" class="rounded-xl bg-ink-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><RefreshCw class="inline mr-2" :size="16"/>Buat kode pairing</button><div v-if="pairing" class="rounded-2xl bg-ink-50 p-5"><p class="text-sm text-ink-600">Kirim pesan berikut ke nomor bot Ledger dalam 10 menit:</p><div class="mt-3 flex items-center justify-between gap-3 rounded-xl border bg-white p-4"><code class="text-lg font-bold">{{ pairing.command }}</code><button @click="copy" class="p-2"><Copy :size="18"/></button></div></div></template><button v-else @click="disconnect" class="rounded-xl border px-4 py-3 text-sm font-semibold"><Unplug class="inline mr-2" :size="16"/>Putuskan WhatsApp</button><div class="border-t pt-5"><p class="font-semibold text-ink-900">Contoh chat</p><div class="mt-3 space-y-2 text-sm text-ink-600"><p>• bensin 50rb bca</p><p>• makan 35k gopay</p><p>• gaji 8jt masuk bca</p></div><p class="mt-4 text-xs text-ink-500">Ledger akan meminta konfirmasi sebelum transaksi disimpan. Groq hanya digunakan sebagai fallback ketika parser lokal tidak yakin.</p></div></div></div></template>
