<script setup>
import {ref} from 'vue';import {storeToRefs} from 'pinia';import {useAuthStore} from '@/stores/auth';import {useRoute} from 'vue-router';
import {LayoutDashboard,Wallet,PiggyBank,Target,BarChart3,History,Settings,LogOut,User,Plus,ScanLine,Menu,X,ReceiptText,Tags,ChevronRight,Bell} from 'lucide-vue-next';import logoImg from '../assets/ledger-icon.png';
const auth=useAuthStore(),{user}=storeToRefs(auth),route=useRoute(),more=ref(false);
const sections=[{label:'Overview',items:[{name:'Dashboard',path:'/dashboard',icon:LayoutDashboard}]},{label:'Money',items:[{name:'Transaksi',path:'/transactions',icon:History},{name:'Akun & Dompet',path:'/accounts',icon:Wallet},{name:'Scan Bukti',path:'/scan',icon:ScanLine}]},{label:'Planning',items:[{name:'Budget',path:'/budget',icon:PiggyBank},{name:'Goals',path:'/goals',icon:Target},{name:'Tagihan',path:'/bills',icon:ReceiptText}]},{label:'Insights',items:[{name:'Laporan',path:'/report',icon:BarChart3}]},{label:'System',items:[{name:'Kategori',path:'/categories',icon:Tags},{name:'Pengaturan',path:'/settings',icon:Settings}]}];
const mobile=[{name:'Beranda',path:'/dashboard',icon:LayoutDashboard},{name:'Transaksi',path:'/transactions',icon:History},{name:'Akun',path:'/accounts',icon:Wallet}];
const active=p=>route.path===p||route.path.startsWith(p+'/');
</script>
<template>
<header class="lg:hidden fixed top-0 inset-x-0 z-40 h-16 bg-paper-0/90 backdrop-blur-xl border-b border-line-200 px-4 flex items-center justify-between"><div class="flex items-center gap-2"><img :src="logoImg" class="w-8 h-8 object-contain"/><b class="tracking-[-.04em] text-lg">Ledger</b></div><div class="flex gap-2"><router-link to="/scan" class="icon-button"><ScanLine class="w-4 h-4"/></router-link><button class="icon-button"><Bell class="w-4 h-4"/></button></div></header>
<aside class="hidden lg:flex w-[270px] h-screen sticky top-0 shrink-0 bg-paper-0 border-r border-line-200 p-4 flex-col">
 <div class="h-16 flex items-center gap-3 px-3"><div class="w-10 h-10 rounded-[14px] bg-primary-100 grid place-items-center"><img :src="logoImg" class="w-7 h-7 object-contain"/></div><div><b class="text-lg tracking-[-.045em]">Ledger</b><span class="block text-[10px] text-ink-400 font-semibold">Personal Finance</span></div></div>
 <nav class="flex-1 overflow-y-auto py-3 no-scrollbar space-y-5"><section v-for="s in sections" :key="s.label"><p class="px-3 mb-1.5 text-[10px] uppercase tracking-[.14em] text-ink-400 font-bold">{{s.label}}</p><router-link v-for="i in s.items" :key="i.path" :to="i.path" class="h-10 px-3 rounded-xl flex items-center gap-3 text-[13px] font-semibold transition" :class="active(i.path)?'bg-primary-100 text-primary-700':'text-ink-600 hover:bg-base-50 hover:text-ink-900'"><component :is="i.icon" class="w-[17px] h-[17px]"/><span>{{i.name}}</span></router-link></section></nav>
 <div class="pt-3 border-t border-line-200"><router-link to="/settings" class="flex items-center gap-3 p-2 rounded-xl hover:bg-base-50"><div class="w-9 h-9 rounded-xl bg-primary-100 text-primary-700 grid place-items-center"><User class="w-4 h-4"/></div><div class="min-w-0 flex-1"><b class="block text-xs truncate">{{user?.name||'User'}}</b><span class="block text-[10px] text-ink-400 truncate">{{user?.email}}</span></div><ChevronRight class="w-4 h-4 text-ink-300"/></router-link><button @click="auth.logout()" class="mt-1 w-full h-9 px-3 rounded-xl flex items-center gap-2 text-xs font-semibold text-expense-600 hover:bg-expense-100"><LogOut class="w-4 h-4"/>Keluar</button></div>
</aside>
<div class="lg:hidden h-16"></div>
<nav class="lg:hidden fixed bottom-0 inset-x-0 z-40 bg-paper-0/94 backdrop-blur-xl border-t border-line-200 px-2 pt-2 pb-safe flex items-end">
 <router-link v-for="i in mobile.slice(0,2)" :key="i.path" :to="i.path" class="flex-1 flex flex-col items-center gap-1 py-1.5 text-[10px] font-semibold" :class="active(i.path)?'text-primary-600':'text-ink-400'"><component :is="i.icon" class="w-5 h-5"/>{{i.name}}</router-link>
 <div class="flex-1 flex justify-center"><router-link to="/transactions/create" aria-label="Tambah transaksi" class="-mt-7 w-14 h-14 rounded-[18px] bg-primary-600 text-white grid place-items-center shadow-violet border-[5px] border-paper-0"><Plus class="w-6 h-6"/></router-link></div>
 <router-link :to="mobile[2].path" class="flex-1 flex flex-col items-center gap-1 py-1.5 text-[10px] font-semibold" :class="active(mobile[2].path)?'text-primary-600':'text-ink-400'"><Wallet class="w-5 h-5"/>Akun</router-link>
 <button @click="more=true" class="flex-1 flex flex-col items-center gap-1 py-1.5 text-[10px] font-semibold text-ink-400"><Menu class="w-5 h-5"/>Lainnya</button>
</nav>
<div v-if="more" class="lg:hidden fixed inset-0 z-50 bg-black/35 backdrop-blur-sm flex items-end" @click="more=false"><div class="w-full max-h-[82vh] overflow-auto bg-paper-0 rounded-t-[28px] p-5 pb-safe" @click.stop><div class="flex items-center justify-between mb-4"><div><b class="text-lg">Menu Ledger</b><p class="text-xs text-ink-500">Semua fitur keuanganmu</p></div><button @click="more=false" class="icon-button"><X class="w-4 h-4"/></button></div><div class="grid grid-cols-2 gap-2"><template v-for="s in sections" :key="s.label"><router-link v-for="i in s.items.filter(x=>!['/dashboard','/transactions','/accounts'].includes(x.path))" :key="i.path" :to="i.path" @click="more=false" class="p-3.5 border border-line-200 rounded-2xl bg-base-50 flex gap-3 items-center"><div class="w-9 h-9 rounded-xl bg-paper-0 grid place-items-center text-primary-600"><component :is="i.icon" class="w-4 h-4"/></div><span class="text-xs font-bold">{{i.name}}</span></router-link></template></div><button @click="auth.logout()" class="mt-4 w-full secondary-button text-expense-600"><LogOut class="w-4 h-4"/>Keluar</button></div></div>
</template>
